BEGIN;
TRUNCATE TABLE detalle_venta, venta, producto, usuario, cliente, empleado, proveedor, categoria RESTART IDENTITY CASCADE;
-- categoria
INSERT INTO categoria (nombre, descripcion) VALUES
('Electronics', 'Smartphones, computers, cameras, and consumer technology devices.'),
('Clothing', 'Everyday apparel for men, women, and teens.'),
('Home Decor', 'Decorative items, lighting, and accents for living spaces.'),
('Sports & Fitness', 'Equipment, accessories, and gear for active lifestyles.'),
('Beauty', 'Skin care, makeup, and personal beauty essentials.'),
('Groceries', 'Packaged food, pantry staples, and everyday household consumables.'),
('Office Supplies', 'Products for printing, organization, and office productivity.'),
('Toys & Games', 'Educational toys, board games, and entertainment for families.'),
('Automotive', 'Replacement parts and maintenance products for vehicles.'),
('Garden', 'Tools and supplies for gardening and outdoor maintenance.'),
('Pet Supplies', 'Food, accessories, and care products for household pets.'),
('Health & Wellness', 'Personal care, wellness products, and health-related items.'),
('Footwear', 'Athletic shoes, casual footwear, and seasonal styles.'),
('Fashion Accessories', 'Bags, belts, watches, and complementary style items.'),
('Kitchenware', 'Cooking, baking, and food preparation essentials.'),
('Furniture', 'Home and dining furniture for residential spaces.'),
('Audio', 'Headphones, speakers, and sound-related electronics.'),
('Gaming', 'Consoles, accessories, and gaming entertainment products.'),
('Mobile Accessories', 'Chargers, cases, cables, and smartphone add-ons.'),
('Outdoor Living', 'Camping and patio products for outdoor activities.'),
('Cleaning Supplies', 'Commercial and household cleaning tools and products.'),
('Baby Care', 'Diapers, hygiene, and essential products for infants.'),
('Stationery', 'Writing instruments, notebooks, and school supplies.'),
('Appliances', 'Small and large appliances for home use.'),
('Jewelry', 'Watches and personal adornment products.');

-- proveedor
INSERT INTO proveedor (nombre, telefono, email, direccion) VALUES
('Apple Distribution Latin America', '+502 2234-1101', 'ventas@applelatam.com', 'Avenida Reforma 12-45, Zona 10, Ciudad de Guatemala'),
('Samsung Electronics Guatemala', '+502 2234-1102', 'comercial@samsunggt.com', 'Boulevard Los Proceres 18-20, Zona 10, Ciudad de Guatemala'),
('Sony Comercial Centroamerica', '+502 2234-1103', 'pedidos@sonyca.com', 'Calzada Roosevelt 25-60, Zona 7, Ciudad de Guatemala'),
('HP Enterprise Supplies', '+502 2234-1104', 'mayoreo@hpenterprise.com', 'Ruta 6 9-15, Zona 4, Ciudad de Guatemala'),
('Nike Retail Partners', '+502 2234-1105', 'wholesale@nikeretailpartners.com', 'Diagonal 6 14-32, Zona 10, Ciudad de Guatemala'),
('Levi Strauss Wholesale', '+502 2234-1106', 'distribucion@leviswholesale.com', 'Avenida Petapa 42-18, Zona 12, Ciudad de Guatemala'),
('Muebles del Bosque', '+502 2234-1107', 'ventas@mueblesdelbosque.com', 'Kilometro 16 Carretera a El Salvador, Fraijanes'),
('Oster Centroamericana', '+502 2234-1108', 'ordenes@osterca.com', 'Anillo Periferico 11-98, Zona 11, Ciudad de Guatemala'),
('Adidas Sports Merchandising', '+502 2234-1109', 'b2b@adidassports.com', 'Centro Comercial Naranjo, Mixco, Guatemala'),
('L''Oreal Beauty Supply', '+502 2234-1110', 'ventas@lorealbeauty.com', 'Avenida Las Americas 7-50, Zona 13, Ciudad de Guatemala'),
('Logitech Business Group', '+502 2234-1111', 'corporate@logitechbg.com', 'Boulevard Liberacion 6-24, Zona 9, Ciudad de Guatemala'),
('KitchenAid Regional Supply', '+502 2234-1112', 'supply@kitchenaidregional.com', 'Ruta al Atlantico 3-90, Zona 17, Ciudad de Guatemala'),
('Coleman Outdoor Wholesale', '+502 2234-1113', 'dealer@colemanwholesale.com', 'Avenida Hincapie 17-61, Zona 13, Ciudad de Guatemala'),
('Michelin Auto Parts GT', '+502 2234-1114', 'ventas@michelinautogt.com', 'Calzada Aguilar Batres 51-30, Zona 12, Ciudad de Guatemala'),
('Purina PetCare Distribution', '+502 2234-1115', 'pedidos@purinapetcare.com', 'Boulevard Principal 4-55, Zona 5, Villa Nueva'),
('Pampers Consumer Goods', '+502 2234-1116', 'mayoreo@pamperscg.com', 'Calzada San Juan 13-40, Mixco, Guatemala'),
('LEGO Retail Distribution', '+502 2234-1117', 'orders@legoretail.com', 'Avenida Simeon Canas 20-11, Zona 2, Ciudad de Guatemala'),
('Casio Timepieces Americas', '+502 2234-1118', 'sales@casiotimepieces.com', 'Boulevard Vista Hermosa 21-09, Zona 15, Ciudad de Guatemala'),
('Whirlpool Home Appliances CA', '+502 2234-1119', 'ventas@whirlpoolca.com', 'Kilometro 14.5 Carretera a El Salvador, Santa Catarina Pinula'),
('Rubbermaid Commercial Supply', '+502 2234-1120', 'orders@rubbermaidcs.com', 'Calzada Mateo Flores 8-70, Zona 3, Ciudad de Guatemala'),
('Pilot Pen Distributors', '+502 2234-1121', 'ventas@pilotdist.com', 'Zona Pradera 9-85, Zona 10, Ciudad de Guatemala'),
('Hasbro Toy Distribution', '+502 2234-1122', 'comercial@hasbrodist.com', 'Avenida Bolivar 30-18, Zona 8, Ciudad de Guatemala'),
('Maybelline Beauty Partners', '+502 2234-1123', 'pedidos@maybellinepartners.com', 'Avenida La Reforma 5-72, Zona 9, Ciudad de Guatemala'),
('Canon Imaging Solutions', '+502 2234-1124', 'b2b@canonimaging.com', 'Centro Empresarial El Cortijo, Zona 14, Ciudad de Guatemala'),
('JBL Audio Wholesale', '+502 2234-1125', 'ventas@jblaudio.com', 'Avenida La Castellana 18-07, Zona 8, Mixco');

-- producto
INSERT INTO producto (nombre, precio, stock, id_categoria, id_proveedor) VALUES
('iPhone 13', 799.00, 18, (SELECT id_categoria FROM categoria WHERE nombre = 'Electronics'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Apple Distribution Latin America')),
('Samsung Galaxy A54', 449.00, 24, (SELECT id_categoria FROM categoria WHERE nombre = 'Electronics'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Samsung Electronics Guatemala')),
('Sony WH-1000XM4 Headphones', 349.00, 15, (SELECT id_categoria FROM categoria WHERE nombre = 'Audio'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Sony Comercial Centroamerica')),
('HP LaserJet Pro M404dn Printer', 279.00, 10, (SELECT id_categoria FROM categoria WHERE nombre = 'Office Supplies'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'HP Enterprise Supplies')),
('Nike Air Zoom Pegasus 40', 129.00, 35, (SELECT id_categoria FROM categoria WHERE nombre = 'Footwear'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Nike Retail Partners')),
('Levi''s 511 Slim Jeans', 69.00, 42, (SELECT id_categoria FROM categoria WHERE nombre = 'Clothing'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Levi Strauss Wholesale')),
('Wooden Dining Table', 649.00, 8, (SELECT id_categoria FROM categoria WHERE nombre = 'Furniture'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Muebles del Bosque')),
('Oster Pro 1200 Blender', 119.00, 20, (SELECT id_categoria FROM categoria WHERE nombre = 'Appliances'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Oster Centroamericana')),
('Adidas Al Rihla League Soccer Ball', 39.00, 30, (SELECT id_categoria FROM categoria WHERE nombre = 'Sports & Fitness'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Adidas Sports Merchandising')),
('L''Oreal Revitalift Hyaluronic Serum', 24.00, 55, (SELECT id_categoria FROM categoria WHERE nombre = 'Beauty'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'L''Oreal Beauty Supply')),
('Logitech MX Master 3S Mouse', 99.00, 27, (SELECT id_categoria FROM categoria WHERE nombre = 'Electronics'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Logitech Business Group')),
('KitchenAid Artisan Stand Mixer', 429.00, 9, (SELECT id_categoria FROM categoria WHERE nombre = 'Appliances'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'KitchenAid Regional Supply')),
('Coleman Sundome 4-Person Tent', 179.00, 14, (SELECT id_categoria FROM categoria WHERE nombre = 'Outdoor Living'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Coleman Outdoor Wholesale')),
('Michelin Primacy 4 Tire 205/55R16', 149.00, 25, (SELECT id_categoria FROM categoria WHERE nombre = 'Automotive'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Michelin Auto Parts GT')),
('Purina Dog Chow Complete 15 kg', 34.00, 40, (SELECT id_categoria FROM categoria WHERE nombre = 'Pet Supplies'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Purina PetCare Distribution')),
('Pampers Premium Care Size 4 Pack', 22.00, 60, (SELECT id_categoria FROM categoria WHERE nombre = 'Baby Care'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Pampers Consumer Goods')),
('LEGO Classic Creative Bricks Set', 49.00, 28, (SELECT id_categoria FROM categoria WHERE nombre = 'Toys & Games'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'LEGO Retail Distribution')),
('Casio G-Shock GA-2100 Watch', 129.00, 16, (SELECT id_categoria FROM categoria WHERE nombre = 'Jewelry'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Casio Timepieces Americas')),
('Whirlpool 14 cu ft Refrigerator', 899.00, 7, (SELECT id_categoria FROM categoria WHERE nombre = 'Appliances'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Whirlpool Home Appliances CA')),
('Rubbermaid WaveBrake Mop Bucket Set', 159.00, 22, (SELECT id_categoria FROM categoria WHERE nombre = 'Cleaning Supplies'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Rubbermaid Commercial Supply')),
('Pilot G2 Gel Pen Pack 12 Units', 11.00, 75, (SELECT id_categoria FROM categoria WHERE nombre = 'Stationery'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Pilot Pen Distributors')),
('Hasbro Monopoly Classic Board Game', 25.00, 26, (SELECT id_categoria FROM categoria WHERE nombre = 'Toys & Games'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Hasbro Toy Distribution')),
('Maybelline Fit Me Matte Foundation', 12.00, 48, (SELECT id_categoria FROM categoria WHERE nombre = 'Beauty'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Maybelline Beauty Partners')),
('Canon EOS R50 Mirrorless Camera', 949.00, 11, (SELECT id_categoria FROM categoria WHERE nombre = 'Electronics'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'Canon Imaging Solutions')),
('JBL Charge 5 Portable Speaker', 149.00, 19, (SELECT id_categoria FROM categoria WHERE nombre = 'Audio'), (SELECT id_proveedor FROM proveedor WHERE nombre = 'JBL Audio Wholesale'));

-- cliente
INSERT INTO cliente (nombre, apellido, email, telefono) VALUES
('Ana', 'Morales', 'ana.morales@gmail.com', '+502 5412-1001'),
('Jorge', 'Castillo', 'jorge.castillo@gmail.com', '+502 5412-1002'),
('Valeria', 'Ramirez', 'valeria.ramirez@yahoo.com', '+502 5412-1003'),
('Diego', 'Herrera', 'diego.herrera@gmail.com', '+502 5412-1004'),
('Camila', 'Soto', 'camila.soto@hotmail.com', '+502 5412-1005'),
('Luis', 'Mejia', 'luis.mejia@gmail.com', '+502 5412-1006'),
('Mariana', 'Lopez', 'mariana.lopez@yahoo.com', '+502 5412-1007'),
('Pablo', 'Ortiz', 'pablo.ortiz@gmail.com', '+502 5412-1008'),
('Sofia', 'Gutierrez', 'sofia.gutierrez@gmail.com', '+502 5412-1009'),
('Andres', 'Molina', 'andres.molina@hotmail.com', '+502 5412-1010'),
('Gabriela', 'Perez', 'gabriela.perez@gmail.com', '+502 5412-1011'),
('Ricardo', 'Arias', 'ricardo.arias@yahoo.com', '+502 5412-1012'),
('Laura', 'Vasquez', 'laura.vasquez@gmail.com', '+502 5412-1013'),
('Fernando', 'Rosales', 'fernando.rosales@gmail.com', '+502 5412-1014'),
('Elena', 'Reyes', 'elena.reyes@hotmail.com', '+502 5412-1015'),
('Mateo', 'Navarro', 'mateo.navarro@gmail.com', '+502 5412-1016'),
('Paola', 'Mendez', 'paola.mendez@yahoo.com', '+502 5412-1017'),
('Daniel', 'Sandoval', 'daniel.sandoval@gmail.com', '+502 5412-1018'),
('Ximena', 'Aguilar', 'ximena.aguilar@gmail.com', '+502 5412-1019'),
('Roberto', 'Fuentes', 'roberto.fuentes@hotmail.com', '+502 5412-1020'),
('Isabella', 'Cabrera', 'isabella.cabrera@gmail.com', '+502 5412-1021'),
('Sergio', 'Leon', 'sergio.leon@yahoo.com', '+502 5412-1022'),
('Natalia', 'Escobar', 'natalia.escobar@gmail.com', '+502 5412-1023'),
('Victor', 'Salazar', 'victor.salazar@gmail.com', '+502 5412-1024'),
('Adriana', 'Romero', 'adriana.romero@hotmail.com', '+502 5412-1025');

-- empleado
INSERT INTO empleado (nombre, apellido, cargo, salario) VALUES
('Carlos', 'Mendoza', 'Gerente de tienda', 12500.00),
('Andrea', 'Lopez', 'Subgerente', 9800.00),
('Jose', 'Ramirez', 'Supervisor de ventas', 7200.00),
('Maria Fernanda', 'Cruz', 'Cajera', 4500.00),
('Kevin', 'Morales', 'Cajero', 4400.00),
('Lucia', 'Herrera', 'Asesora de ventas', 4300.00),
('Esteban', 'Perez', 'Asesor de ventas', 4300.00),
('Natalia', 'Gomez', 'Coordinadora de inventario', 6800.00),
('Oscar', 'Castillo', 'Auxiliar de bodega', 4100.00),
('Daniela', 'Vega', 'Analista de compras', 7500.00),
('Pablo', 'Reyes', 'Encargado de servicio al cliente', 5200.00),
('Claudia', 'Torres', 'Visual merchandiser', 5600.00),
('Hector', 'Diaz', 'Supervisor de caja', 6100.00),
('Patricia', 'Aguilar', 'Encargada de electronica', 5900.00),
('Miguel', 'Soto', 'Encargado de deportes', 5400.00),
('Carolina', 'Fuentes', 'Encargada de belleza', 5300.00),
('Alejandro', 'Pineda', 'Encargado de hogar', 5300.00),
('Veronica', 'Salazar', 'Recursos humanos', 7800.00),
('Javier', 'Monzon', 'Contador', 8200.00),
('Melissa', 'Cifuentes', 'Asistente administrativa', 5000.00),
('Fernando', 'Cabrera', 'Jefe de bodega', 7000.00),
('Tatiana', 'Leon', 'Especialista de marketing', 6500.00),
('Raul', 'Escobar', 'Soporte tecnico', 6200.00),
('Sofia', 'Barrios', 'Compradora junior', 4800.00),
('Ivan', 'Rosales', 'Prevencion de perdidas', 4700.00);

-- usuario
INSERT INTO usuario (username, password_hash, nombre_mostrar, id_empleado) VALUES
('admin', '3e01f3708b4dda9da8b984bcd792618d6b81d88aa1182e3ba87212ada3e341c8', 'Administrador general', (SELECT id_empleado FROM empleado WHERE nombre = 'Carlos' AND apellido = 'Mendoza')),
('ventas', '3e01f3708b4dda9da8b984bcd792618d6b81d88aa1182e3ba87212ada3e341c8', 'Supervisor de ventas', (SELECT id_empleado FROM empleado WHERE nombre = 'Jose' AND apellido = 'Ramirez')),
('inventario', '3e01f3708b4dda9da8b984bcd792618d6b81d88aa1182e3ba87212ada3e341c8', 'Coordinacion de inventario', (SELECT id_empleado FROM empleado WHERE nombre = 'Natalia' AND apellido = 'Gomez'));

-- venta
INSERT INTO venta (fecha, id_cliente, id_empleado) VALUES
(DATE '2025-09-03', (SELECT id_cliente FROM cliente WHERE email = 'ana.morales@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Maria Fernanda' AND apellido = 'Cruz')),
(DATE '2025-09-05', (SELECT id_cliente FROM cliente WHERE email = 'jorge.castillo@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Kevin' AND apellido = 'Morales')),
(DATE '2025-09-12', (SELECT id_cliente FROM cliente WHERE email = 'valeria.ramirez@yahoo.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Lucia' AND apellido = 'Herrera')),
(DATE '2025-09-18', (SELECT id_cliente FROM cliente WHERE email = 'diego.herrera@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Esteban' AND apellido = 'Perez')),
(DATE '2025-10-01', (SELECT id_cliente FROM cliente WHERE email = 'camila.soto@hotmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Patricia' AND apellido = 'Aguilar')),
(DATE '2025-10-08', (SELECT id_cliente FROM cliente WHERE email = 'luis.mejia@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Miguel' AND apellido = 'Soto')),
(DATE '2025-10-14', (SELECT id_cliente FROM cliente WHERE email = 'mariana.lopez@yahoo.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Carolina' AND apellido = 'Fuentes')),
(DATE '2025-10-25', (SELECT id_cliente FROM cliente WHERE email = 'pablo.ortiz@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Maria Fernanda' AND apellido = 'Cruz')),
(DATE '2025-11-02', (SELECT id_cliente FROM cliente WHERE email = 'sofia.gutierrez@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Kevin' AND apellido = 'Morales')),
(DATE '2025-11-11', (SELECT id_cliente FROM cliente WHERE email = 'andres.molina@hotmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Lucia' AND apellido = 'Herrera')),
(DATE '2025-11-21', (SELECT id_cliente FROM cliente WHERE email = 'gabriela.perez@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Esteban' AND apellido = 'Perez')),
(DATE '2025-12-03', (SELECT id_cliente FROM cliente WHERE email = 'ricardo.arias@yahoo.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Patricia' AND apellido = 'Aguilar')),
(DATE '2025-12-10', (SELECT id_cliente FROM cliente WHERE email = 'laura.vasquez@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Miguel' AND apellido = 'Soto')),
(DATE '2025-12-19', (SELECT id_cliente FROM cliente WHERE email = 'fernando.rosales@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Carolina' AND apellido = 'Fuentes')),
(DATE '2026-01-07', (SELECT id_cliente FROM cliente WHERE email = 'elena.reyes@hotmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Maria Fernanda' AND apellido = 'Cruz')),
(DATE '2026-01-15', (SELECT id_cliente FROM cliente WHERE email = 'mateo.navarro@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Kevin' AND apellido = 'Morales')),
(DATE '2026-01-29', (SELECT id_cliente FROM cliente WHERE email = 'paola.mendez@yahoo.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Lucia' AND apellido = 'Herrera')),
(DATE '2026-02-06', (SELECT id_cliente FROM cliente WHERE email = 'daniel.sandoval@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Esteban' AND apellido = 'Perez')),
(DATE '2026-02-18', (SELECT id_cliente FROM cliente WHERE email = 'ximena.aguilar@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Patricia' AND apellido = 'Aguilar')),
(DATE '2026-03-02', (SELECT id_cliente FROM cliente WHERE email = 'roberto.fuentes@hotmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Miguel' AND apellido = 'Soto')),
(DATE '2026-03-11', (SELECT id_cliente FROM cliente WHERE email = 'isabella.cabrera@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Carolina' AND apellido = 'Fuentes')),
(DATE '2026-03-19', (SELECT id_cliente FROM cliente WHERE email = 'sergio.leon@yahoo.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Maria Fernanda' AND apellido = 'Cruz')),
(DATE '2026-03-28', (SELECT id_cliente FROM cliente WHERE email = 'natalia.escobar@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Kevin' AND apellido = 'Morales')),
(DATE '2026-04-05', (SELECT id_cliente FROM cliente WHERE email = 'victor.salazar@gmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Lucia' AND apellido = 'Herrera')),
(DATE '2026-04-14', (SELECT id_cliente FROM cliente WHERE email = 'adriana.romero@hotmail.com'), (SELECT id_empleado FROM empleado WHERE nombre = 'Esteban' AND apellido = 'Perez'));

-- detalle_venta
INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario) VALUES
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-09-03'), (SELECT id_producto FROM producto WHERE nombre = 'iPhone 13'), 1, 799.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-09-03'), (SELECT id_producto FROM producto WHERE nombre = 'JBL Charge 5 Portable Speaker'), 1, 149.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-09-05'), (SELECT id_producto FROM producto WHERE nombre = 'Nike Air Zoom Pegasus 40'), 1, 129.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-09-05'), (SELECT id_producto FROM producto WHERE nombre = 'Adidas Al Rihla League Soccer Ball'), 2, 39.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-09-12'), (SELECT id_producto FROM producto WHERE nombre = 'Levi''s 511 Slim Jeans'), 2, 69.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-09-12'), (SELECT id_producto FROM producto WHERE nombre = 'Maybelline Fit Me Matte Foundation'), 1, 12.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-09-18'), (SELECT id_producto FROM producto WHERE nombre = 'Sony WH-1000XM4 Headphones'), 1, 349.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-09-18'), (SELECT id_producto FROM producto WHERE nombre = 'Logitech MX Master 3S Mouse'), 1, 99.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-10-01'), (SELECT id_producto FROM producto WHERE nombre = 'Wooden Dining Table'), 1, 649.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-10-01'), (SELECT id_producto FROM producto WHERE nombre = 'Pilot G2 Gel Pen Pack 12 Units'), 3, 11.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-10-08'), (SELECT id_producto FROM producto WHERE nombre = 'Oster Pro 1200 Blender'), 1, 119.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-10-08'), (SELECT id_producto FROM producto WHERE nombre = 'KitchenAid Artisan Stand Mixer'), 1, 429.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-10-14'), (SELECT id_producto FROM producto WHERE nombre = 'Coleman Sundome 4-Person Tent'), 1, 179.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-10-14'), (SELECT id_producto FROM producto WHERE nombre = 'Purina Dog Chow Complete 15 kg'), 2, 34.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-10-25'), (SELECT id_producto FROM producto WHERE nombre = 'Samsung Galaxy A54'), 1, 449.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-10-25'), (SELECT id_producto FROM producto WHERE nombre = 'Casio G-Shock GA-2100 Watch'), 1, 129.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-11-02'), (SELECT id_producto FROM producto WHERE nombre = 'Pampers Premium Care Size 4 Pack'), 3, 22.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-11-02'), (SELECT id_producto FROM producto WHERE nombre = 'Maybelline Fit Me Matte Foundation'), 2, 12.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-11-11'), (SELECT id_producto FROM producto WHERE nombre = 'Canon EOS R50 Mirrorless Camera'), 1, 949.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-11-11'), (SELECT id_producto FROM producto WHERE nombre = 'Sony WH-1000XM4 Headphones'), 1, 349.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-11-21'), (SELECT id_producto FROM producto WHERE nombre = 'Michelin Primacy 4 Tire 205/55R16'), 4, 149.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-11-21'), (SELECT id_producto FROM producto WHERE nombre = 'Rubbermaid WaveBrake Mop Bucket Set'), 1, 159.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-12-03'), (SELECT id_producto FROM producto WHERE nombre = 'LEGO Classic Creative Bricks Set'), 2, 49.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-12-03'), (SELECT id_producto FROM producto WHERE nombre = 'Hasbro Monopoly Classic Board Game'), 1, 25.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-12-10'), (SELECT id_producto FROM producto WHERE nombre = 'Whirlpool 14 cu ft Refrigerator'), 1, 899.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-12-10'), (SELECT id_producto FROM producto WHERE nombre = 'Rubbermaid WaveBrake Mop Bucket Set'), 1, 159.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-12-19'), (SELECT id_producto FROM producto WHERE nombre = 'HP LaserJet Pro M404dn Printer'), 1, 279.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2025-12-19'), (SELECT id_producto FROM producto WHERE nombre = 'Pilot G2 Gel Pen Pack 12 Units'), 5, 11.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-01-07'), (SELECT id_producto FROM producto WHERE nombre = 'L''Oreal Revitalift Hyaluronic Serum'), 2, 24.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-01-07'), (SELECT id_producto FROM producto WHERE nombre = 'Maybelline Fit Me Matte Foundation'), 2, 12.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-01-15'), (SELECT id_producto FROM producto WHERE nombre = 'Nike Air Zoom Pegasus 40'), 1, 129.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-01-15'), (SELECT id_producto FROM producto WHERE nombre = 'Levi''s 511 Slim Jeans'), 1, 69.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-01-29'), (SELECT id_producto FROM producto WHERE nombre = 'Samsung Galaxy A54'), 1, 449.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-01-29'), (SELECT id_producto FROM producto WHERE nombre = 'Pampers Premium Care Size 4 Pack'), 2, 22.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-02-06'), (SELECT id_producto FROM producto WHERE nombre = 'Coleman Sundome 4-Person Tent'), 1, 179.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-02-06'), (SELECT id_producto FROM producto WHERE nombre = 'Adidas Al Rihla League Soccer Ball'), 1, 39.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-02-18'), (SELECT id_producto FROM producto WHERE nombre = 'KitchenAid Artisan Stand Mixer'), 1, 429.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-02-18'), (SELECT id_producto FROM producto WHERE nombre = 'Oster Pro 1200 Blender'), 1, 119.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-03-02'), (SELECT id_producto FROM producto WHERE nombre = 'Purina Dog Chow Complete 15 kg'), 1, 34.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-03-02'), (SELECT id_producto FROM producto WHERE nombre = 'JBL Charge 5 Portable Speaker'), 1, 149.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-03-11'), (SELECT id_producto FROM producto WHERE nombre = 'Wooden Dining Table'), 1, 649.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-03-11'), (SELECT id_producto FROM producto WHERE nombre = 'Casio G-Shock GA-2100 Watch'), 1, 129.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-03-19'), (SELECT id_producto FROM producto WHERE nombre = 'Logitech MX Master 3S Mouse'), 2, 99.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-03-19'), (SELECT id_producto FROM producto WHERE nombre = 'Pilot G2 Gel Pen Pack 12 Units'), 4, 11.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-03-28'), (SELECT id_producto FROM producto WHERE nombre = 'Hasbro Monopoly Classic Board Game'), 1, 25.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-03-28'), (SELECT id_producto FROM producto WHERE nombre = 'LEGO Classic Creative Bricks Set'), 1, 49.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-04-05'), (SELECT id_producto FROM producto WHERE nombre = 'iPhone 13'), 1, 799.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-04-05'), (SELECT id_producto FROM producto WHERE nombre = 'Sony WH-1000XM4 Headphones'), 1, 349.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-04-14'), (SELECT id_producto FROM producto WHERE nombre = 'HP LaserJet Pro M404dn Printer'), 1, 279.00),
((SELECT id_venta FROM venta WHERE fecha = DATE '2026-04-14'), (SELECT id_producto FROM producto WHERE nombre = 'Samsung Galaxy A54'), 1, 449.00);

COMMIT;
